# Generated by Django 3.1.1 on 2020-10-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('course_number', models.IntegerField(blank=True, default='', max_length=10)),
                ('instructor_name', models.CharField(blank=True, default='', max_length=50)),
                ('duration', models.FloatField(blank=True, default='', max_length=6)),
            ],
        ),
    ]
